name: my_project_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.10.*
  - conda-lock
  - mamba
  - pip # pip must be mentioned explicitly, or conda-lock will fail
  - setuptools
  - poetry=1.6.*
  - pytorch::pytorch=2.1.0
  - pytorch::pytorch-cuda=12.1

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
