[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
# --------- pytorch --------- #
torch = "2.3.1"
torchvision = "^0.18.1"
lightning = "^2.3.0"
torchmetrics = "^1.4.0"
# --------- hydra --------- #
hydra-core = "1.3.2"
hydra-colorlog = "^1.2.0"
hydra-optuna-sweeper = "^1.2.0"
# --------- data --------- #
pandas = "^2.2.2"
numpy = "^1.26.4"
scipy = "^1.13.1"
scikit-learn = "^1.5.0"
jupyter = "^1.0.0"
matplotlib = "^3.9.0"
plotly = "^5.22.0"
scikit-image = "^0.23.2"
albumentations = "^1.4.8"
opencv-python-headless = "^4.10.0.82"
# --------- loggers --------- #
# tensorboard = "^2.12.0"
wandb = "^0.17.1"
# neptune-client
# mlflow
# comet-ml
# --------- others --------- #
rootutils = "^1.0.7"       # standardizing the project root setup
pre-commit = "^3.7.1"      # hooks for applying linters on commit
rich = "^13.7.1"           # beautiful text formatting in terminal
pytest = "^8.2.2"          # tests
pytest-cov = "^4.1.0"
sh = { version = "^1.14.3", markers = "sys_platform == 'linux' or sys_platform == 'darwin'" }
gdown = "^5.2.0"
fastapi = "^0.111.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--color=yes",
    "--durations=0",
    "--strict-markers",
    "--doctest-modules",
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]
log_cli = "True"
markers = [
    "slow: slow tests",
]
minversion = "6.0"
testpaths = "tests/"

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]
