[tool.poetry]
name = "ultrasound-fetal-images"
version = "0.1.0"
description = ""
authors = ["Aleksander Zamojski <zamojski96@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
# --------- pytorch --------- #
torch = "2.0.0"
torchvision = "^0.15.1"
lightning = "^2.0.0"
torchmetrics = "^0.11.4"
# --------- hydra --------- #
hydra-core = "1.3.2"
hydra-colorlog = "^1.2.0"
hydra-optuna-sweeper = "^1.2.0"
# --------- data --------- #
pandas = "^1.5.3"
numpy = "^1.24.2"
scikit-learn = "^1.2.2"
jupyter = "^1.0.0"
matplotlib = "^3.7.1"
plotly = "^5.13.1"
opencv-python = "^4.7.0.72"
scikit-image = "^0.20.0"
albumentations = "^1.3.0"
# --------- loggers --------- #
# tensorboard = "^2.12.0"
wandb = "^0.13.11"
# neptune-client
# mlflow
# comet-ml
# --------- others --------- #
pyrootutils = "^1.0.4"     # standardizing the project root setup
pre-commit = "^3.4.0"      # hooks for applying linters on commit
rich = "^13.3.2"           # beautiful text formatting in terminal
pytest = "^7.2.2"          # tests
pytest-cov = "^4.0.0"
sh = { version = "^1.14.3", markers = "sys_platform == 'linux' or sys_platform == 'darwin'" }
gdown = "^4.6.4"
fastapi = ">=0.80"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--color=yes",
    "--durations=0",
    "--strict-markers",
    "--doctest-modules",
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]
log_cli = "True"
markers = [
    "slow: slow tests",
]
minversion = "6.0"
testpaths = "tests/"

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]
