[tool.poetry]
name = "ultrasound-fetal-images"
version = "0.1.0"
description = ""
authors = ["Aleksander Zamojski <zamojski96@gmail.com>"]
readme = "README.md"
packages = [{ include = "ultrasound_fetal_images" }]

[tool.poetry.dependencies]
python = "^3.10"
# --------- pytorch --------- #
torch = "^1.13.0"
torchvision = "^0.14.0"
pytorch-lightning = "1.8.4"
torchmetrics = "^0.11.0"
# --------- hydra --------- #
hydra-core = "1.3.0"
hydra-colorlog = "^1.2.0"
# --------- others --------- #
pyrootutils = "^1.0.4"     # standardizing the project root setup
pre-commit = "^2.20.0"     # hooks for applying linters on commit
rich = "^12.6.0"           # beautiful text formatting in terminal
pytest = "^7.2.0"          # tests
sh = "^1.14.3"             # for running bash commands in some tests (linux/macos only)

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--color=yes",
    "--durations=0",
    "--strict-markers",
    "--doctest-modules",
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]
log_cli = "True"
markers = [
    "slow: slow tests",
]
minversion = "6.0"
testpaths = "tests/"

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]
