defaults:
  - default.yaml

# log plot to wandb
after_test_plots:
  _target_: src.utils.plots.PlotVideoQuality
  enabled: true
  data_dir: null
  dataset_name: null
  samples: 5
  beans: 10
  img_size: [165, 240]
