defaults:
  - default

# log plot to wandb
after_test_plots:
  _target_: src.utils.plots.PlotVideosProbabilities
  enabled: false
  data_dir: ${paths.data_dir}
  video_dataset_dir: ""
  batch_size: ${data.batch_size}
  input_size: ${data.input_size}
  min_probabilities:
    [0.0, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.96, 0.97, 0.98, 0.99, 0.995]
  probability_norm: 1.0
