_target_: src.models.fetal_module.FetalLitModule

criterion:
  _target_: torch.nn.CrossEntropyLoss
  _partial_: true
  label_smoothing: 0.0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

#scheduler:
#  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#  _partial_: true
#  mode: min
#  factor: 0.1
#  patience: 5

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 5
  gamma: 0.1

#scheduler:
#  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
#  _partial_: true
#  T_max: ??
#  eta_min: 0

net_spec:
  name: "densenet169"
  output_size: ${model.num_classes}
  pretrain: true

num_classes: 5
