_target_: src.models.fetal_module.FetalLitModule

criterion:
  _target_: torch.nn.CrossEntropyLoss
  _partial_: true
  reduction: "mean"
  label_smoothing: 0.0

lr: 0.001

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

#scheduler:
#  _target_: torch.optim.lr_scheduler.StepLR
#  _partial_: true
#  step_size: 5
#  gamma: 0.1

#scheduler:
#  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
#  _partial_: true
#  T_max: ??
#  eta_min: 0

net_spec:
  name: "mobilenet_v3_small"
  output_size: ${model.num_classes}
  pretrain: true

num_classes: 5

softmax_target: False

vta_transforms:
  horizontal_flips: [False]
  rotate_degrees: [0]
  translates: [[0.0, 0.0]]
  scales: [1.0]

tta_transforms:
  horizontal_flips: [False, True]
  rotate_degrees: [0]
  translates: [[0.0, 0.0]]
  scales: [1.0]
