_target_: src.models.fetal_module.FetalLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

#scheduler:
#  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#  _partial_: true
#  mode: min
#  factor: 0.1
#  patience: 10

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 5
  gamma: 0.1

net_spec:
  name: "densenet169"
  output_size: ${model.num_classes}
  pretrain: true

num_classes: 5
