_target_: src.models.head_segmentation_module.HeadSegmentationLitModule

model:
  _target_: segmentation_models_pytorch.Unet
  _partial_: true
  encoder_name: mobilenet_v2
  encoder_weights: imagenet
  in_channels: 1
  classes: 1
  activation:

criterion:
  _target_: src.models.components.loss.BinaryDiceCrossEntropyLoss
  _partial_: true

lr: 0.001

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  weight_decay: 0.0
  amsgrad: false

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5
