_target_: src.models.head_segmentation_module.HeadSegmentationLitModule

criterion:
  _target_: src.models.components.loss.BinaryDiceCrossEntropyLoss
  _partial_: true
  smooth: 1.0
  weight:

lr: 0.001

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5
