defaults:
  - _self_
  - paths: default
  - hydra: default

# task name, determines output directory path
task_name: "create_quality_dataset"

model_path: "logs/train/runs/2023-06-26_12-06-59"
device: "auto" # cpu, cuda, auto
dataset_dir: "US_VIDEOS_tran_2106_playful-haze-2111"
image_height: 165
image_width: 240
batch_size: 350
window: 3
temperature: 1.0
