defaults:
  - _self_
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. the best hyperparameters for given model and data
  - experiment: null

# task name, determines output directory path
task_name: "create_quality_dataset"

model_path: "logs/train/runs/2023-06-26_12-06-59"
device: "auto" # cpu, cuda, auto
video_dir: "US_VIDEOS"
dataset_dir: "US_VIDEOS"

sample: false
google_file_id: "1rKWhPg9lltY_dWMah9aN6pqs3H_ri-0a"

image_height: 55
image_width: 80

horizontal_flips: [False, True]
vertical_flips: [False]
rotate_degrees: [0]
translates: [[0.0, 0.0]]
scales: [1.0]

batch_size: 64
window: 3
gma_width: 3
temperature: 1.0
