defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml

# task name, determines output directory path
task_name: "create_quality_dataset"

model_path: "logs/train/runs/2023-02-25_19-43-37"
device: "auto" # cpu, cuda, auto
dataset_dir: "US_VIDEOS_tran_630"
image_height: 165
image_width: 240
batch_size: 315
window: 3
temperature: 1.0
